name: "Testing Pull Request"

on:
  pull_request:
    branches:
      - "master"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.8, 3.9]
        
    steps:
    - uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge,defaults
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies on Linux/MacOS
      if: startsWith(matrix.os, 'windows') != true
      run: |
        conda install --yes pythonocc-core
        python3 -m pip install --upgrade pip
        python3 -m pip install smithers[vtk]
        python3 -m pip install .[test]
        
    - name: Install Python dependencies on Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        conda install --yes pythonocc-core
        python -m pip install --upgrade pip
        python -m pip install smithers[vtk]
        python -m pip install .[test]

    - name: Test with pytest on Windows
      if: startsWith(matrix.os, 'windows')
      run: python -m pytest

    - name: Test with pytest on Linux/MacOS
      if: startsWith(matrix.os, 'windows') != true
      run: python3 -m pytest
